# Generated by Django 5.1.7 on 2026-06-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diet_preference',
            field=models.CharField(choices=[('anything', 'Anything (No restrictions)'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Ketogenic (Keto)'), ('pescatarian', 'Pescatarian')], default='anything', max_length=20),
        ),
    ]
