# Generated by Django 5.1.7 on 2026-06-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_diet_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal_weight',
            field=models.FloatField(blank=True, help_text='Target goal weight in kg', null=True),
        ),
    ]
