version: '3.8'
services:
  web:
    build:
      context: ./backend
    command: gunicorn backend.config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nainsi!0098
    ports:
      - "5432:5432"
