services:
  - type: web
    name: dietplanner-backend
    env: python
    rootDirectory: backend
    plan: free

    buildCommand: bash build.sh

    startCommand: >-
      python manage.py migrate --noinput &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:$PORT
      --workers 2
      --timeout 120
      --access-logfile -
      --error-logfile -

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.15
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: DB_ENGINE
        value: postgresql
      - key: DB_HOST
        value: aws-1-ap-southeast-1.pooler.supabase.com
      - key: DB_NAME
        value: postgres
      - key: DB_PORT
        value: "6543"
      - key: DB_USER
        value: postgres
      - key: FRONTEND_URL
        value: https://dietplanner.vercel.app
      - key: ALLOWED_HOSTS
        value: dietplanner-1-b8jo.onrender.com,localhost
      - key: DB_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DB_PROJECT_REF
        sync: false

    healthCheckPath: /api/health/

    autoDeploy: true
