# Generated by Django 5.1.7 on 2026-06-24 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserYogaStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_days', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yoga_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YogaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(help_text='YouTube Video ID (e.g. dQw4w9WgXcQ)', max_length=50)),
                ('category', models.CharField(choices=[('weight_loss', 'Weight Loss Yoga'), ('weight_gain', 'Weight Gain Yoga'), ('belly_fat', 'Belly Fat Reduction Yoga'), ('stress_relief', 'Meditation for Stress Relief'), ('morning', 'Morning Yoga Routine'), ('beginner', 'Beginner Yoga Classes')], max_length=30)),
                ('duration_mins', models.IntegerField(default=15)),
                ('instructor', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('calorie_burn', models.IntegerField(default=100, help_text='Estimated calories burned')),
                ('flexibility', models.CharField(default='Medium', help_text='Flexibility benefit level (Low/Medium/High)', max_length=15)),
                ('relaxation', models.CharField(default='Medium', help_text='Relaxation benefit level (Low/Medium/High)', max_length=15)),
                ('strength', models.CharField(default='Medium', help_text='Strength benefit level (Low/Medium/High)', max_length=15)),
                ('recommended_goal', models.CharField(choices=[('loss', 'Weight Loss'), ('gain', 'Weight Gain'), ('lifestyle', 'Fitness/Lifestyle'), ('maintenance', 'Stress Management/Maintenance')], default='lifestyle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='bookmarked_yoga_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YogaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoga_logs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.yogavideo')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
