# Generated by Django 6.0.6 on 2026-07-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogavideo',
            name='video_source',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('dailymotion', 'Dailymotion')], default='youtube', max_length=20),
        ),
        migrations.AlterField(
            model_name='yogavideo',
            name='category',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss Yoga'), ('weight_gain', 'Weight Gain Yoga'), ('belly_fat', 'Belly Fat Reduction Yoga'), ('stress_relief', 'Meditation for Stress Relief'), ('morning', 'Morning Yoga Routine'), ('beginner', 'Beginner Yoga Classes'), ('yoga', 'General Yoga'), ('meditation', 'General Meditation')], max_length=30),
        ),
    ]
