# Generated by Django 5.1.7 on 2026-06-23 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymealcompletion',
            name='fiber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailymealcompletion',
            name='sugar',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('walking', 'Walking'), ('running', 'Running'), ('cycling', 'Cycling'), ('gym', 'Gym Workout'), ('other', 'Other Exercise')], default='walking', max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('calories_burned', models.FloatField(help_text='Calories burned in kcal')),
                ('steps', models.IntegerField(default=0, help_text='Number of steps')),
                ('logged_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='WellnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_hours', models.FloatField(default=0.0, help_text='Hours of sleep')),
                ('mood', models.CharField(choices=[('happy', 'Happy 😊'), ('neutral', 'Neutral 😐'), ('energetic', 'Energetic ⚡'), ('tired', 'Tired 😴'), ('stressed', 'Stressed 😰'), ('sad', 'Sad 😢')], default='neutral', max_length=15)),
                ('energy_level', models.IntegerField(default=5, help_text='Energy level from 1-10')),
                ('stress_level', models.IntegerField(default=5, help_text='Stress level from 1-10')),
                ('logged_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
                'unique_together': {('user', 'logged_at')},
            },
        ),
    ]
