// ─── Rich Food Mock Database ──────────────────────────────────────────────────

export const FOOD_IMAGES = {
  'Grilled Chicken Breast': 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&q=80',
  'Brown Rice': 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80',
  'Whole Egg': 'https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=400&q=80',
  'Avocado': 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&q=80',
  'Greek Yogurt': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80',
  'Oats': 'https://images.unsplash.com/photo-1568254183919-78a4f43a2877?w=400&q=80',
  'Salmon Fillet': 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&q=80',
  'Paneer': 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80',
  'Banana': 'https://images.unsplash.com/photo-1481349518771-20055b2a7b24?w=400&q=80',
  'Almonds': 'https://images.unsplash.com/photo-1574570523624-37a9f16ffef4?w=400&q=80',
  'Quinoa': 'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=400&q=80',
  'Spinach': 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80',
  'Sweet Potato': 'https://images.unsplash.com/photo-1596097559926-3b9e5f7f3b0e?w=400&q=80',
  'Dal Tadka': 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80',
  'Idli': 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80',
};

export const FALLBACK_IMAGE = 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80';

export const MOCK_FOODS = [
  {
    id: 'f001',
    name: 'Grilled Chicken Breast',
    category: 'Protein',
    serving_size: '100g',
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    cholesterol: 85,
    saturated_fat: 1.0,
    potassium: 256,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&q=80',
    health_score: 94,
    glycemic_index: 0,
    gi_label: 'N/A',
    diet_tags: ['High Protein', 'Gluten-Free', 'Dairy-Free', 'Keto'],
    meal_types: ['Lunch', 'Dinner'],
    allergens: [],
    cuisine: 'Continental',
    vitamins: { B12: 28, B6: 60, D: 2, A: 1, C: 3, E: 2 },
    minerals: { Iron: 6, Calcium: 1, Potassium: 7, Magnesium: 7, Phosphorus: 22 },
    ingredients: ['Chicken breast', 'Olive oil', 'Garlic', 'Herbs', 'Salt', 'Pepper'],
    is_verified: true,
    is_trending: true,
    rating: 4.8,
    reviews_count: 312,
    ai_tips: [
      'Excellent for muscle building — 31g of complete protein per 100g.',
      'Low fat makes it ideal for weight loss and heart health goals.',
      'Pair with brown rice and veggies for a complete macronutrient meal.',
    ],
    ai_alternative: 'Turkey breast (similar protein, slightly lower fat)',
    ai_portion: '150-200g for active adults post-workout',
    community_submitted: false,
    reviews: [
      { user: 'FitFoodie', rating: 5, comment: 'Best lean protein source!', avatar: '💪' },
      { user: 'NutriNerd', rating: 5, comment: 'Versatile and nutritious.', avatar: '🥗' },
    ],
  },
  {
    id: 'f002',
    name: 'Brown Rice',
    category: 'Grains',
    serving_size: '1 cup cooked (195g)',
    calories: 216,
    protein: 5,
    carbs: 45,
    fats: 1.8,
    fiber: 3.5,
    sugar: 0.7,
    sodium: 10,
    cholesterol: 0,
    saturated_fat: 0.4,
    potassium: 84,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80',
    health_score: 80,
    glycemic_index: 68,
    gi_label: 'Medium',
    diet_tags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free'],
    meal_types: ['Lunch', 'Dinner'],
    allergens: [],
    cuisine: 'Indian',
    vitamins: { B1: 19, B3: 15, B6: 14, B12: 0, D: 0, A: 0, C: 0, E: 2 },
    minerals: { Iron: 5, Calcium: 2, Potassium: 2, Magnesium: 21, Phosphorus: 16 },
    ingredients: ['Brown rice', 'Water', 'Salt'],
    is_verified: true,
    is_trending: false,
    rating: 4.5,
    reviews_count: 178,
    ai_tips: [
      'Higher fiber than white rice — keeps you fuller longer.',
      'Ideal for sustained energy; pair with lean protein.',
      'GI of 68 — moderate, so watch portion size if diabetic.',
    ],
    ai_alternative: 'Quinoa (higher protein, lower GI at 53)',
    ai_portion: '½ cup cooked for weight loss, 1 cup for maintenance',
    community_submitted: false,
    reviews: [
      { user: 'HealthyEater', rating: 5, comment: 'A staple in my diet!', avatar: '🍚' },
      { user: 'DiabetesDietitian', rating: 4, comment: 'Good but watch portions.', avatar: '👩‍⚕️' },
    ],
  },
  {
    id: 'f003',
    name: 'Whole Egg',
    category: 'Protein',
    serving_size: '1 large egg (50g)',
    calories: 78,
    protein: 6,
    carbs: 0.6,
    fats: 5,
    fiber: 0,
    sugar: 0.6,
    sodium: 62,
    cholesterol: 186,
    saturated_fat: 1.6,
    potassium: 63,
    image: 'https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=400&q=80',
    health_score: 88,
    glycemic_index: 0,
    gi_label: 'N/A',
    diet_tags: ['Vegetarian', 'High Protein', 'Keto', 'Gluten-Free'],
    meal_types: ['Breakfast', 'Lunch', 'Snack'],
    allergens: ['Eggs'],
    cuisine: 'Continental',
    vitamins: { B12: 19, D: 11, A: 8, B2: 13, E: 4, C: 0 },
    minerals: { Iron: 5, Calcium: 3, Potassium: 2, Selenium: 28, Phosphorus: 10 },
    ingredients: ['Egg'],
    is_verified: true,
    is_trending: true,
    rating: 4.9,
    reviews_count: 524,
    ai_tips: [
      'Complete protein with all 9 essential amino acids.',
      'Rich in choline — critical for brain health and liver function.',
      'Cholesterol in eggs does not significantly raise blood cholesterol for most people.',
    ],
    ai_alternative: 'Egg whites only (lower calories, zero fat)',
    ai_portion: '2-3 eggs per day for most healthy adults',
    community_submitted: false,
    reviews: [
      { user: 'GymBro', rating: 5, comment: 'Best breakfast ever!', avatar: '🏋️' },
      { user: 'MomOfThree', rating: 5, comment: 'Kids love it!', avatar: '👩‍👧‍👦' },
    ],
  },
  {
    id: 'f004',
    name: 'Avocado',
    category: 'Fruits',
    serving_size: '½ medium (75g)',
    calories: 120,
    protein: 1.5,
    carbs: 6.4,
    fats: 11,
    fiber: 5,
    sugar: 0.4,
    sodium: 5,
    cholesterol: 0,
    saturated_fat: 1.6,
    potassium: 364,
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&q=80',
    health_score: 96,
    glycemic_index: 15,
    gi_label: 'Low',
    diet_tags: ['Vegan', 'Keto', 'Gluten-Free', 'Dairy-Free', 'Low Carb'],
    meal_types: ['Breakfast', 'Lunch', 'Snack'],
    allergens: [],
    cuisine: 'Continental',
    vitamins: { K: 26, B5: 21, B6: 15, B9: 20, C: 17, E: 10, D: 0, A: 3 },
    minerals: { Potassium: 10, Magnesium: 7, Phosphorus: 5, Iron: 3, Calcium: 1 },
    ingredients: ['Avocado'],
    is_verified: true,
    is_trending: true,
    rating: 4.8,
    reviews_count: 289,
    ai_tips: [
      'Monounsaturated fats support heart health and reduce bad cholesterol.',
      'Excellent for pregnancy — high in folate (B9).',
      'Helps absorb fat-soluble vitamins A, D, E, K from other foods.',
    ],
    ai_alternative: 'Hummus (similar healthy fats, more protein)',
    ai_portion: '½ avocado per serving — high in calories',
    community_submitted: false,
    reviews: [
      { user: 'HeartHealthHero', rating: 5, comment: 'Great for cholesterol!', avatar: '❤️' },
      { user: 'KetoKing', rating: 5, comment: 'Keto staple!', avatar: '👑' },
    ],
  },
  {
    id: 'f005',
    name: 'Greek Yogurt',
    category: 'Dairy',
    serving_size: '1 cup (227g)',
    calories: 130,
    protein: 22,
    carbs: 9,
    fats: 0.7,
    fiber: 0,
    sugar: 9,
    sodium: 85,
    cholesterol: 11,
    saturated_fat: 0.2,
    potassium: 240,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80',
    health_score: 91,
    glycemic_index: 11,
    gi_label: 'Low',
    diet_tags: ['Vegetarian', 'High Protein', 'Gluten-Free', 'Low Fat'],
    meal_types: ['Breakfast', 'Snack'],
    allergens: ['Dairy'],
    cuisine: 'Continental',
    vitamins: { B12: 38, B2: 27, A: 5, D: 10, C: 0, E: 1 },
    minerals: { Calcium: 20, Phosphorus: 22, Potassium: 7, Magnesium: 5, Zinc: 11 },
    ingredients: ['Milk', 'Live active cultures'],
    is_verified: true,
    is_trending: false,
    rating: 4.7,
    reviews_count: 198,
    ai_tips: [
      'Probiotics support gut health and immune function.',
      'Very high protein for a dairy product — great post-workout snack.',
      'Choose plain, unsweetened to avoid added sugars.',
    ],
    ai_alternative: 'Coconut yogurt (dairy-free alternative)',
    ai_portion: '1 cup daily — excellent protein source',
    community_submitted: false,
    reviews: [
      { user: 'GutHealthGuru', rating: 5, comment: 'Best probiotic food!', avatar: '🦠' },
      { user: 'ProteinQueen', rating: 4, comment: '22g protein is incredible.', avatar: '💪' },
    ],
  },
  {
    id: 'f006',
    name: 'Oats',
    category: 'Grains',
    serving_size: '½ cup dry (40g)',
    calories: 148,
    protein: 5.5,
    carbs: 27,
    fats: 2.5,
    fiber: 4,
    sugar: 0.5,
    sodium: 3,
    cholesterol: 0,
    saturated_fat: 0.4,
    potassium: 143,
    image: 'https://images.unsplash.com/photo-1568254183919-78a4f43a2877?w=400&q=80',
    health_score: 90,
    glycemic_index: 55,
    gi_label: 'Medium',
    diet_tags: ['Vegetarian', 'Vegan', 'High Fiber', 'Dairy-Free'],
    meal_types: ['Breakfast'],
    allergens: ['Gluten'],
    cuisine: 'Continental',
    vitamins: { B1: 26, B5: 10, B6: 7, B9: 7, D: 0, A: 0, C: 0, E: 2 },
    minerals: { Iron: 19, Magnesium: 16, Phosphorus: 20, Zinc: 14, Manganese: 96 },
    ingredients: ['Rolled oats'],
    is_verified: true,
    is_trending: false,
    rating: 4.6,
    reviews_count: 412,
    ai_tips: [
      'Beta-glucan fiber lowers LDL cholesterol by 5-10%.',
      'Keeps blood sugar stable — great for diabetes and PCOS.',
      'Add protein powder or eggs to increase satiety.',
    ],
    ai_alternative: 'Ragi porridge (calcium-rich, gluten-free)',
    ai_portion: '½ cup dry oats = 1 serving, don\'t exceed 1 cup',
    community_submitted: false,
    reviews: [
      { user: 'DiabetesDietitian', rating: 5, comment: 'Best breakfast for blood sugar!', avatar: '👩‍⚕️' },
      { user: 'FitnessFreak', rating: 5, comment: 'My pre-workout go-to.', avatar: '🏃' },
    ],
  },
  {
    id: 'f007',
    name: 'Salmon Fillet',
    category: 'Protein',
    serving_size: '100g',
    calories: 208,
    protein: 20,
    carbs: 0,
    fats: 13,
    fiber: 0,
    sugar: 0,
    sodium: 59,
    cholesterol: 63,
    saturated_fat: 3.1,
    potassium: 363,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&q=80',
    health_score: 97,
    glycemic_index: 0,
    gi_label: 'N/A',
    diet_tags: ['High Protein', 'Gluten-Free', 'Dairy-Free', 'Keto', 'Low Carb'],
    meal_types: ['Lunch', 'Dinner'],
    allergens: ['Fish'],
    cuisine: 'Continental',
    vitamins: { B12: 127, D: 97, B3: 50, B6: 47, B5: 19, A: 5, E: 5, C: 3 },
    minerals: { Potassium: 10, Phosphorus: 24, Selenium: 36, Iron: 3, Magnesium: 8 },
    ingredients: ['Atlantic salmon'],
    is_verified: true,
    is_trending: true,
    rating: 4.9,
    reviews_count: 267,
    ai_tips: [
      'Omega-3 fatty acids (EPA/DHA) reduce inflammation and support heart health.',
      'Highest natural source of Vitamin D — critical for bone and immune health.',
      'Eat 2-3 servings per week for maximum cardiovascular benefit.',
    ],
    ai_alternative: 'Mackerel or sardines (similar Omega-3, more affordable)',
    ai_portion: '100-150g per serving, 2-3x per week',
    community_submitted: false,
    reviews: [
      { user: 'HeartDoc', rating: 5, comment: 'Best food for heart health!', avatar: '🫀' },
      { user: 'OmegaFan', rating: 5, comment: 'Worth every penny.', avatar: '🐟' },
    ],
  },
  {
    id: 'f008',
    name: 'Paneer',
    category: 'Dairy',
    serving_size: '100g',
    calories: 265,
    protein: 18,
    carbs: 3.4,
    fats: 20,
    fiber: 0,
    sugar: 3.4,
    sodium: 364,
    cholesterol: 66,
    saturated_fat: 13,
    potassium: 99,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80',
    health_score: 72,
    glycemic_index: 27,
    gi_label: 'Low',
    diet_tags: ['Vegetarian', 'High Protein', 'Gluten-Free', 'Keto'],
    meal_types: ['Lunch', 'Dinner', 'Snack'],
    allergens: ['Dairy'],
    cuisine: 'Indian',
    vitamins: { A: 15, B12: 10, D: 8, B2: 12, C: 0, E: 2, K: 3, B9: 5 },
    minerals: { Calcium: 48, Phosphorus: 30, Potassium: 3, Iron: 3, Zinc: 10 },
    ingredients: ['Full-fat milk', 'Lemon juice or vinegar'],
    is_verified: true,
    is_trending: false,
    rating: 4.7,
    reviews_count: 341,
    ai_tips: [
      'Best vegetarian source of calcium — 48% RDA per 100g.',
      'High in saturated fat; consume in moderation for heart health.',
      'Low GI makes it suitable for diabetics in small portions.',
    ],
    ai_alternative: 'Tofu (lower fat, similar protein, vegan-friendly)',
    ai_portion: '50-80g per meal is sufficient',
    community_submitted: false,
    reviews: [
      { user: 'VegFoodie', rating: 5, comment: 'Best Indian protein!', avatar: '🧀' },
      { user: 'FitIndian', rating: 4, comment: 'High fat but very filling.', avatar: '💪' },
    ],
  },
  {
    id: 'f009',
    name: 'Banana',
    category: 'Fruits',
    serving_size: '1 medium (118g)',
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fats: 0.4,
    fiber: 3.1,
    sugar: 14,
    sodium: 1,
    cholesterol: 0,
    saturated_fat: 0.1,
    potassium: 422,
    image: 'https://images.unsplash.com/photo-1481349518771-20055b2a7b24?w=400&q=80',
    health_score: 79,
    glycemic_index: 51,
    gi_label: 'Low-Medium',
    diet_tags: ['Vegan', 'Gluten-Free', 'Dairy-Free'],
    meal_types: ['Breakfast', 'Snack'],
    allergens: [],
    cuisine: 'Indian',
    vitamins: { B6: 20, C: 17, B9: 6, A: 1, D: 0, E: 1, K: 1, B1: 4 },
    minerals: { Potassium: 12, Magnesium: 8, Phosphorus: 3, Iron: 2, Manganese: 16 },
    ingredients: ['Banana'],
    is_verified: true,
    is_trending: false,
    rating: 4.5,
    reviews_count: 509,
    ai_tips: [
      'Potassium helps prevent muscle cramps — ideal pre/post workout.',
      'Natural sugars provide quick energy burst for athletes.',
      'Ripe bananas have higher GI — green bananas are more diabetic-friendly.',
    ],
    ai_alternative: 'Apple (lower sugar, similar fiber)',
    ai_portion: '1 medium banana as a pre-workout snack',
    community_submitted: false,
    reviews: [
      { user: 'RunnerGal', rating: 5, comment: 'Perfect pre-race fuel!', avatar: '🏃‍♀️' },
      { user: 'YogaMom', rating: 4, comment: 'Kids love it!', avatar: '🧘‍♀️' },
    ],
  },
  {
    id: 'f010',
    name: 'Almonds',
    category: 'Nuts',
    serving_size: '28g (handful)',
    calories: 164,
    protein: 6,
    carbs: 6,
    fats: 14,
    fiber: 3.5,
    sugar: 1.2,
    sodium: 0,
    cholesterol: 0,
    saturated_fat: 1.1,
    potassium: 200,
    image: 'https://images.unsplash.com/photo-1574570523624-37a9f16ffef4?w=400&q=80',
    health_score: 92,
    glycemic_index: 0,
    gi_label: 'Very Low',
    diet_tags: ['Vegan', 'Keto', 'Gluten-Free', 'Dairy-Free', 'High Fiber'],
    meal_types: ['Snack', 'Breakfast'],
    allergens: ['Nuts'],
    cuisine: 'Continental',
    vitamins: { E: 37, B2: 17, B3: 5, B9: 5, D: 0, A: 0, C: 0, K: 0 },
    minerals: { Magnesium: 19, Calcium: 8, Iron: 6, Phosphorus: 15, Zinc: 6 },
    ingredients: ['Raw almonds'],
    is_verified: true,
    is_trending: true,
    rating: 4.8,
    reviews_count: 423,
    ai_tips: [
      'Vitamin E in almonds is a potent antioxidant protecting cell membranes.',
      'Reduces bad LDL cholesterol when eaten regularly.',
      'Soak overnight for better nutrient absorption and digestibility.',
    ],
    ai_alternative: 'Walnuts (higher Omega-3, similar calories)',
    ai_portion: '28g (about 23 almonds) is one serving',
    community_submitted: false,
    reviews: [
      { user: 'NutLover', rating: 5, comment: 'Best snack ever!', avatar: '🥜' },
      { user: 'HeartNurse', rating: 5, comment: 'Heart-healthy perfection.', avatar: '❤️' },
    ],
  },
  {
    id: 'f011',
    name: 'Quinoa',
    category: 'Grains',
    serving_size: '1 cup cooked (185g)',
    calories: 222,
    protein: 8,
    carbs: 39,
    fats: 3.5,
    fiber: 5,
    sugar: 1.6,
    sodium: 13,
    cholesterol: 0,
    saturated_fat: 0.4,
    potassium: 318,
    image: 'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=400&q=80',
    health_score: 93,
    glycemic_index: 53,
    gi_label: 'Low-Medium',
    diet_tags: ['Vegan', 'Gluten-Free', 'High Protein', 'Dairy-Free'],
    meal_types: ['Lunch', 'Dinner', 'Breakfast'],
    allergens: [],
    cuisine: 'Continental',
    vitamins: { B1: 13, B2: 12, B9: 19, B6: 11, E: 4, D: 0, A: 0, C: 0 },
    minerals: { Iron: 15, Magnesium: 30, Phosphorus: 28, Zinc: 13, Manganese: 58 },
    ingredients: ['Quinoa', 'Water'],
    is_verified: true,
    is_trending: true,
    rating: 4.7,
    reviews_count: 215,
    ai_tips: [
      'One of the only plant foods with all 9 essential amino acids.',
      'Perfect for vegans needing complete protein.',
      'High magnesium supports muscle recovery and sleep quality.',
    ],
    ai_alternative: 'Amaranth (similar nutrition, different texture)',
    ai_portion: '1 cup cooked per meal',
    community_submitted: false,
    reviews: [
      { user: 'VeganAthlete', rating: 5, comment: 'Complete protein perfection!', avatar: '🌱' },
      { user: 'GlutenFreeGal', rating: 5, comment: 'Safe and nutritious!', avatar: '🌾' },
    ],
  },
  {
    id: 'f012',
    name: 'Spinach',
    category: 'Vegetables',
    serving_size: '1 cup raw (30g)',
    calories: 7,
    protein: 0.9,
    carbs: 1.1,
    fats: 0.1,
    fiber: 0.7,
    sugar: 0.1,
    sodium: 24,
    cholesterol: 0,
    saturated_fat: 0,
    potassium: 167,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80',
    health_score: 99,
    glycemic_index: 15,
    gi_label: 'Very Low',
    diet_tags: ['Vegan', 'Keto', 'Gluten-Free', 'Dairy-Free', 'Low Carb', 'Low Fat'],
    meal_types: ['Breakfast', 'Lunch', 'Dinner', 'Snack'],
    allergens: [],
    cuisine: 'Continental',
    vitamins: { K: 145, A: 56, C: 14, B9: 15, E: 5, B6: 6, B2: 9, D: 0 },
    minerals: { Iron: 5, Calcium: 3, Magnesium: 6, Potassium: 5, Manganese: 13 },
    ingredients: ['Baby spinach'],
    is_verified: true,
    is_trending: false,
    rating: 4.4,
    reviews_count: 267,
    ai_tips: [
      'Iron + Vitamin C combo in spinach maximizes iron absorption.',
      'Nitrates in spinach improve athletic performance and blood flow.',
      'Lutein and zeaxanthin protect eye health and reduce macular degeneration risk.',
    ],
    ai_alternative: 'Kale (higher Vitamin C, similar nutrients)',
    ai_portion: '2 cups raw = 1 generous serving (very low calories)',
    community_submitted: false,
    reviews: [
      { user: 'Popeye', rating: 5, comment: 'Makes me strong!', avatar: '💪' },
      { user: 'NutritionNerd', rating: 5, comment: 'Most nutrient-dense vegetable!', avatar: '🥬' },
    ],
  },
  {
    id: 'f013',
    name: 'Dal Tadka',
    category: 'Protein',
    serving_size: '1 bowl (250g)',
    calories: 190,
    protein: 12,
    carbs: 28,
    fats: 4,
    fiber: 8,
    sugar: 2,
    sodium: 380,
    cholesterol: 0,
    saturated_fat: 0.5,
    potassium: 410,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80',
    health_score: 86,
    glycemic_index: 32,
    gi_label: 'Low',
    diet_tags: ['Vegetarian', 'Vegan', 'Gluten-Free', 'High Fiber', 'Budget Friendly'],
    meal_types: ['Lunch', 'Dinner'],
    allergens: [],
    cuisine: 'Indian',
    vitamins: { B9: 45, B1: 22, B6: 15, C: 5, A: 3, D: 0, E: 2, K: 5 },
    minerals: { Iron: 22, Magnesium: 18, Phosphorus: 20, Potassium: 12, Zinc: 8 },
    ingredients: ['Toor dal', 'Onion', 'Tomato', 'Garlic', 'Cumin', 'Turmeric', 'Ghee', 'Red chilli'],
    is_verified: true,
    is_trending: false,
    rating: 4.8,
    reviews_count: 412,
    ai_tips: [
      'Excellent source of folate — important for pregnancy.',
      'Complete amino acid profile when paired with rice.',
      'Low GI with high fiber — ideal for blood sugar management.',
    ],
    ai_alternative: 'Rajma curry (higher protein, similar fiber)',
    ai_portion: '1 bowl (250g) with 1 cup rice for a balanced meal',
    community_submitted: true,
    reviews: [
      { user: 'ChaiAndCurry', rating: 5, comment: 'Desi comfort food at its best!', avatar: '🍛' },
      { user: 'VeganIndia', rating: 5, comment: 'High protein plant meal!', avatar: '🌿' },
    ],
  },
  {
    id: 'f014',
    name: 'Idli',
    category: 'Grains',
    serving_size: '2 pieces (100g)',
    calories: 78,
    protein: 3.4,
    carbs: 15.9,
    fats: 0.4,
    fiber: 0.5,
    sugar: 0.3,
    sodium: 340,
    cholesterol: 0,
    saturated_fat: 0.1,
    potassium: 85,
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80',
    health_score: 82,
    glycemic_index: 69,
    gi_label: 'Medium',
    diet_tags: ['Vegetarian', 'Vegan', 'Dairy-Free', 'Budget Friendly'],
    meal_types: ['Breakfast', 'Snack'],
    allergens: ['Gluten'],
    cuisine: 'Indian',
    vitamins: { B1: 10, B2: 8, B9: 6, C: 0, A: 0, D: 0, E: 1, K: 0 },
    minerals: { Iron: 4, Calcium: 3, Potassium: 2, Magnesium: 5, Phosphorus: 8 },
    ingredients: ['Urad dal', 'Rice', 'Salt', 'Water'],
    is_verified: true,
    is_trending: false,
    rating: 4.6,
    reviews_count: 328,
    ai_tips: [
      'Fermentation boosts B vitamins and improves gut health.',
      'Low calorie — 4-5 idlis = 150-180 kcal, great for weight loss.',
      'Pair with sambar for a protein-complete meal.',
    ],
    ai_alternative: 'Dosa (crispier, slightly higher fat)',
    ai_portion: '2-4 idlis per meal depending on your calorie target',
    community_submitted: true,
    reviews: [
      { user: 'SouthIndianFoodie', rating: 5, comment: 'Light and healthy!', avatar: '🍚' },
      { user: 'WeightWatcher', rating: 5, comment: 'Perfect low-calorie breakfast.', avatar: '⚖️' },
    ],
  },
];

// ─── Trending Foods ───────────────────────────────────────────────────────────
export const TRENDING_FOODS = [
  'Grilled Chicken', 'Quinoa Bowl', 'Greek Yogurt', 'Avocado Toast',
  'Salmon', 'Almonds', 'Dal Tadka', 'Oats', 'Paneer Tikka', 'Egg White'
];

// ─── Popular Searches ─────────────────────────────────────────────────────────
export const POPULAR_SEARCHES = [
  { query: 'high protein breakfast', emoji: '💪' },
  { query: 'low calorie snacks', emoji: '🥗' },
  { query: 'indian vegan foods', emoji: '🌿' },
  { query: 'keto foods list', emoji: '🥑' },
  { query: 'best pre workout meal', emoji: '🏋️' },
];

// ─── Community-Submitted Foods ───────────────────────────────────────────────
export const COMMUNITY_FOODS = [
  {
    id: 'c001',
    name: 'Protein Banana Pancakes',
    user: 'FitFoodie22',
    avatar: '👨‍🍳',
    rating: 4.7,
    reviews: 34,
    calories: 220,
    protein: 18,
    carbs: 24,
    fats: 5,
    image: 'https://images.unsplash.com/photo-1565299543923-37dd37887442?w=400&q=80',
    is_verified: false,
    likes: 128,
    timeAgo: '2 days ago',
    tags: ['High Protein', 'Breakfast', 'Vegetarian'],
  },
  {
    id: 'c002',
    name: 'Overnight Chia Oats',
    user: 'HealthyMamaJi',
    avatar: '👩‍🍳',
    rating: 4.9,
    reviews: 67,
    calories: 320,
    protein: 14,
    carbs: 45,
    fats: 8,
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400&q=80',
    is_verified: true,
    likes: 284,
    timeAgo: '5 hours ago',
    tags: ['Vegan', 'High Fiber', 'Breakfast'],
  },
  {
    id: 'c003',
    name: 'Palak Tofu Sabzi',
    user: 'VeganDesi',
    avatar: '🌱',
    rating: 4.5,
    reviews: 23,
    calories: 145,
    protein: 12,
    carbs: 10,
    fats: 6,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80',
    is_verified: false,
    likes: 92,
    timeAgo: '1 day ago',
    tags: ['Vegan', 'High Protein', 'Indian'],
  },
];

// ─── Daily Intake Context (for nutrition insights panel) ──────────────────────
export const DAILY_GOAL = {
  calories: 2000,
  protein: 120,
  carbs: 250,
  fats: 65,
  fiber: 30,
  water: 2500, // ml
};

export const TODAY_CONSUMED = {
  calories: 1240,
  protein: 72,
  carbs: 145,
  fats: 38,
  fiber: 16,
  water: 1800,
};

// ─── Nutrient Display helpers ─────────────────────────────────────────────────
export function getHealthScoreColor(score) {
  if (score >= 85) return '#10b981';
  if (score >= 65) return '#f59e0b';
  return '#ef4444';
}

export function getHealthScoreLabel(score) {
  if (score >= 85) return 'Excellent';
  if (score >= 70) return 'Good';
  if (score >= 50) return 'Fair';
  return 'Poor';
}

export function getMacroColor(macro) {
  const map = {
    calories: '#ef4444',
    protein: '#10b981',
    carbs: '#6366f1',
    fats: '#f59e0b',
    fiber: '#06b6d4',
    sugar: '#f97316',
    sodium: '#8b5cf6',
  };
  return map[macro] || '#94a3b8';
}

export function getGIColor(gi) {
  if (!gi || gi === 0) return '#94a3b8';
  if (gi <= 55) return '#10b981';
  if (gi <= 70) return '#f59e0b';
  return '#ef4444';
}

export function categorizeFood(food) {
  if (food.protein > 15) return 'High Protein';
  if (food.fiber > 4) return 'High Fiber';
  if (food.calories < 100) return 'Low Cal';
  return 'Balanced';
}

// ─── Infinite Food Generator ──────────────────────────────────────────────────
export const PAGE_SIZE = 12;

const GEN_NAMES = [
  'Grilled Tofu Steak', 'Lentil Soup', 'Chia Seed Pudding', 'Peanut Butter',
  'Cottage Cheese', 'Chickpea Salad', 'Moong Dal', 'Ragi Roti', 'Rajma Curry',
  'Poha', 'Sprout Bhel', 'Makhana', 'Sattu Drink', 'Besan Chilla',
  'Whey Protein Shake', 'Turkey Breast', 'Black Bean Bowl', 'Edamame',
  'Tempeh', 'Seitan', 'Cauliflower Rice', 'Zucchini Noodles', 'Kale Chips',
  'Beetroot Salad', 'Millet Khichdi', 'Jowar Roti', 'Bajra Roti', 'Corn Salad',
  'Mushroom Soup', 'Broccoli Stir Fry', 'Pumpkin Curry', 'Amla Juice',
  'Tuna Salad', 'Boiled Peanuts', 'Soya Chunks', 'Flaxseed Mix',
  'Coconut Chutney', 'Carrot Sticks', 'Apple Slices', 'Cucumber Raita',
  'Dahi Rice', 'Rajgira Ladoo', 'Dates', 'Walnuts', 'Pumpkin Seeds',
  'Sunflower Seeds', 'Hemp Seeds', 'Nut Butter Toast', 'Protein Pancakes',
  'Egg Bhurji', 'Veggie Omelette', 'Smoothie Bowl', 'Acai Bowl',
  'Fruit Chaat', 'Roasted Chana', 'Puffed Rice', 'Sambar', 'Rasam',
  'Curd Rice', 'Upma', 'Pongal', 'Dhokla', 'Khandvi', 'Thepla',
  'Missi Roti', 'Sabudana Khichdi', 'Modak', 'Poha Chivda',
  'Multigrain Bread', 'Brown Bread', 'Rice Cakes', 'Oat Biscuits',
  'Protein Bar', 'Granola', 'Trail Mix', 'Dry Fruit Mix', 'Roasted Almonds',
  'Steamed Broccoli', 'Boiled Sweet Potato', 'Air-Fried Chickpeas',
  'Spinach Smoothie', 'Green Detox Juice', 'Coconut Water', 'Buttermilk',
  'Lassi', 'Masala Chai (low sugar)', 'Herbal Tea', 'Turmeric Milk',
  'Bone Broth', 'Collagen Drink', 'Electrolyte Water', 'Watermelon Juice',
  'Pomegranate Juice', 'Carrot Ginger Juice', 'Beet & Apple Juice',
  'Palak Soup', 'Tomato Soup', 'Mixed Veggie Soup', 'Miso Soup',
  'Tofu Scramble', 'Vegan Burger Patty', 'Bean Tacos', 'Guacamole',
  'Hummus', 'Baba Ganoush', 'Tzatziki', 'Fattoush Salad', 'Tabbouleh',
];

const GEN_CATEGORIES = ['Protein', 'Grains', 'Fruits', 'Vegetables', 'Nuts', 'Dairy', 'Fats', 'General'];

const GEN_CUISINES = ['Indian', 'Continental', 'Asian', 'Mediterranean', 'Mexican'];

const GEN_DIET_COMBOS = [
  ['Vegetarian', 'Gluten-Free', 'High Fiber'],
  ['Vegan', 'Dairy-Free', 'Low Carb'],
  ['High Protein', 'Keto', 'Gluten-Free'],
  ['Vegetarian', 'High Protein', 'Budget Friendly'],
  ['Vegan', 'High Fiber', 'Dairy-Free'],
  ['Gluten-Free', 'Dairy-Free', 'Low Fat'],
  ['High Protein', 'Low Carb', 'Keto'],
  ['Vegetarian', 'Vegan', 'Budget Friendly'],
];

const GEN_MEAL_COMBOS = [
  ['Breakfast', 'Snack'],
  ['Lunch', 'Dinner'],
  ['Breakfast'],
  ['Lunch', 'Dinner', 'Snack'],
  ['Snack'],
  ['Breakfast', 'Lunch'],
];

const GEN_IMAGES = [
  'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
  'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400&q=80',
  'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&q=80',
  'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80',
  'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80',
  'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=400&q=80',
  'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&q=80',
  'https://images.unsplash.com/photo-1563379091339-03246963d5a4?w=400&q=80',
  'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80',
  'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80',
  'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80',
  'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80',
  'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400&q=80',
  'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&q=80',
  'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&q=80',
  'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&q=80',
  'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&q=80',
  'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80',
  'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&q=80',
  'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80',
  'https://images.unsplash.com/photo-1568254183919-78a4f43a2877?w=400&q=80',
  'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&q=80',
  'https://images.unsplash.com/photo-1481349518771-20055b2a7b24?w=400&q=80',
  'https://images.unsplash.com/photo-1574570523624-37a9f16ffef4?w=400&q=80',
  'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80',
  'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=400&q=80',
];

const GEN_AI_TIPS = [
  'Rich in micronutrients — great for overall wellbeing.',
  'High antioxidant content supports cellular health.',
  'Excellent source of plant-based nutrition.',
  'Ideal for weight management when portion-controlled.',
  'Supports gut health with natural prebiotics.',
  'Good source of slow-digesting complex carbohydrates.',
  'Helps maintain stable blood sugar levels throughout the day.',
  'Rich in omega fatty acids for heart health.',
  'Provides sustained energy without blood sugar spikes.',
  'High thermic effect — helps boost metabolism.',
];

// Stable pseudo-random number seeded by index
function seededRand(seed, min, max) {
  const x = Math.sin(seed * 9301 + 49297) * 233280;
  const r = x - Math.floor(x);
  return Math.floor(r * (max - min + 1)) + min;
}
function pickByIndex(arr, seed) {
  return arr[seededRand(seed, 0, arr.length - 1)];
}

/**
 * Generates a unique, deterministic food item by index.
 * index=0 → first generated food, stable across re-renders.
 */
export function generateFoodItem(index) {
  const seed = index + 1000; // offset so it doesn't clash with MOCK_FOODS ids

  const name = GEN_NAMES[index % GEN_NAMES.length];
  const category = pickByIndex(GEN_CATEGORIES, seed + 1);
  const cuisine = pickByIndex(GEN_CUISINES, seed + 2);
  const dietTags = GEN_DIET_COMBOS[(index + seed) % GEN_DIET_COMBOS.length];
  const mealTypes = GEN_MEAL_COMBOS[(index * 3 + seed) % GEN_MEAL_COMBOS.length];
  const image = GEN_IMAGES[index % GEN_IMAGES.length];
  const healthScore = seededRand(seed + 5, 60, 98);
  const calories = seededRand(seed + 6, 50, 500);
  const protein = seededRand(seed + 7, 1, 35);
  const carbs = seededRand(seed + 8, 2, 60);
  const fats = seededRand(seed + 9, 0, 25);
  const fiber = seededRand(seed + 10, 0, 10);
  const sugar = seededRand(seed + 11, 0, 20);
  const sodium = seededRand(seed + 12, 5, 500);
  const gi = seededRand(seed + 13, 10, 85);
  const giLabel = gi <= 55 ? 'Low' : gi <= 70 ? 'Medium' : 'High';
  const rating = (seededRand(seed + 14, 38, 50)) / 10;
  const reviewsCount = seededRand(seed + 15, 12, 480);
  const isTrending = seededRand(seed + 16, 0, 5) === 0;
  const isVerified = seededRand(seed + 17, 0, 3) > 0;
  const tipIdx = seededRand(seed + 18, 0, GEN_AI_TIPS.length - 1);

  const gi_label = gi <= 55 ? 'Low' : gi <= 70 ? 'Medium' : 'High';

  return {
    id: `gen_${index}`,
    name,
    category,
    serving_size: pickByIndex(['100g', '1 cup', '1 serving', '½ cup', '1 piece', '28g'], seed + 3),
    calories,
    protein,
    carbs,
    fats,
    fiber,
    sugar,
    sodium,
    cholesterol: seededRand(seed + 19, 0, 80),
    saturated_fat: parseFloat((seededRand(seed + 20, 0, 80) / 10).toFixed(1)),
    potassium: seededRand(seed + 21, 50, 500),
    image,
    health_score: healthScore,
    glycemic_index: gi,
    gi_label,
    diet_tags: dietTags,
    meal_types: mealTypes,
    allergens: [],
    cuisine,
    vitamins: {
      B12: seededRand(seed + 22, 0, 40),
      B6: seededRand(seed + 23, 0, 30),
      D: seededRand(seed + 24, 0, 20),
      C: seededRand(seed + 25, 0, 50),
      A: seededRand(seed + 26, 0, 30),
      E: seededRand(seed + 27, 0, 15),
    },
    minerals: {
      Iron: seededRand(seed + 28, 0, 25),
      Calcium: seededRand(seed + 29, 0, 30),
      Potassium: seededRand(seed + 30, 0, 20),
      Magnesium: seededRand(seed + 31, 0, 25),
    },
    ingredients: ['Natural ingredients', 'No artificial additives'],
    is_verified: isVerified,
    is_trending: isTrending,
    community_submitted: false,
    rating,
    reviews_count: reviewsCount,
    ai_tips: [GEN_AI_TIPS[tipIdx]],
    ai_alternative: 'A similar whole-food alternative',
    ai_portion: '1 standard serving as recommended by a nutritionist',
    reviews: [],
  };
}

/**
 * Returns a page of generated food items.
 * page=0 → items 0-11, page=1 → 12-23, etc.
 */
export function getFoodPage(page, pageSize = PAGE_SIZE) {
  return Array.from({ length: pageSize }, (_, i) => generateFoodItem(page * pageSize + i));
}

