# Generated by Django 5.1.7 on 2026-06-22 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='Separate ingredients with a newline or custom delimiter')),
                ('instructions', models.TextField(help_text='Separate steps with a newline')),
                ('prep_time', models.IntegerField(default=10, help_text='in minutes')),
                ('cook_time', models.IntegerField(default=20, help_text='in minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('video_url', models.CharField(blank=True, help_text='YouTube embed link', max_length=300, null=True)),
                ('calories', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('fats', models.FloatField(default=0.0)),
                ('fiber', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
